### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by MatheusWFranca** [GianCastle/FiraMonaco#4]
Hello Gian

Can you please help with the installation? 

I am trying to set up  her in vscode using the following specs but is not working.

 "editor.fontFamily": "Ligamonacop",

Thank you!

**Comment by GianCastle** [comment]
Hi, @MatheusWFranca  🙌🏾

Try with this font name on VSCode!
`Monaco for Powerline`

**Comment by MatheusWFranca** [comment]
It's working now, thanks!
