### ISSUE TITLE
Removed 'fi' and 'fl' ligatures to improve clarity

### ISSUE THREAD

**Issue by dongheeleeme** [GianCastle/FiraMonaco#5]
Hi, @GianCastle

I see 'fi' and 'fl' looks weird when enable ligatures. It is better to remove 'fi' and 'fl' ligatures to improve clarity.

Thank you!

## Ligatures
![Screenshot 2021-02-08 at 16 31 39](https://user-images.githubusercontent.com/38916112/107242522-5a3d3c80-6a2c-11eb-950d-bebd91a00592.png)

## Normal
![Screenshot 2021-02-08 at 16 31 52](https://user-images.githubusercontent.com/38916112/107242402-3679f680-6a2c-11eb-8632-dae485035c73.png)

**Comment by JulindM** [comment]
I think that is not a spacing problem, but that looks rather like a  "f" ligature. If you see closely its ligaturizing fi as one.

**Comment by rjorge99** [comment]
> tter-spacing issue on enabling ligatures [on 23 May](#event-6657968157)

Hi, I just generated some Monaco Fonts with Ligatures and NerdFont applied to them. You could try them out and see if they work for you.

**Comment by dongheeleeme** [comment]
Hi @GianCastle, I need your favor. Could you please delete this issue?
